flask_app/recipes/routes.py
import base64,io
from io import BytesIO
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user
from .. import recipe_client
from ..forms import RecipeReviewForm, SearchForm
from ..models import User, RecipeReview
from ..utils import current_time
import math

recipes = Blueprint("recipes", __name__)
""" ************ Helper for pictures uses username to get their profile picture************ """
def get_b64_img(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

""" ************ View functions ************ """


@recipes.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    random_recipes = None
    try:
        random_recipes = recipe_client.get_random_recipes()
    except Exception as e:
        print(f"Error fetching random recipes: {e}")

    if form.validate_on_submit():
        return redirect(url_for("recipes.query_results", query=form.search_query.data))

    return render_template("index.html", form=form, random_recipes=random_recipes)


@recipes.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    page = request.args.get('page', 1, type=int)
    try:
        results = recipe_client.search(query, page=page)
    except ValueError as e:
        return render_template("query.html", error_msg=str(e))

    total_results = results["totalResults"]
    total_pages = math.ceil(total_results / 30)
    return render_template("query.html", results=results["results"], query=query, page=page, total_pages=total_pages)


@recipes.route("/recipes/<recipe_id>", methods=["GET", "POST"])
def recipe_detail(recipe_id):
    """Displays recipe details and allows users to leave reviews."""
    try:
        result = recipe_client.get_recipe(recipe_id)  
        if not result:
            return render_template("404.html"), 404
    except Exception as e:
        return render_template("error.html", error_msg=str(e))

    form = RecipeReviewForm()
    if form.validate_on_submit():
        review = RecipeReview(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            recipe_id=recipe_id,
            recipe_title=result.title,
            rating=form.rating.data,
            image=get_b64_img(current_user.username)
        )

        review.save()

        return redirect(request.path)

    reviews = RecipeReview.objects(recipe_id=recipe_id)

    return render_template("recipe_detail.html", form=form, recipe=result, reviews=reviews)

@recipes.route("/user/<username>")
def user_detail(username):
    """Displays user details and their reviews."""
    user = User.objects(username=username).first()
    if not user:
        return render_template("404.html"), 404
    reviews = RecipeReview.objects(commenter=user)
    image = get_b64_img(user.username)

    return render_template("user_detail.html", user=user, image=image, reviews=reviews)

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user
import base64
from io import BytesIO
from .. import bcrypt
from werkzeug.utils import secure_filename
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateProfilePicForm
from ..models import User
from ..recipes.routes import get_b64_img


users = Blueprint("users", __name__)

""" ************ User Management views ************ """


# TODO: implement
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
     #Check if authenticated
    if current_user.is_authenticated:
        return redirect(url_for('recipess.index'))
    
    if form.validate_on_submit():
        user = User(
            username = form.username.data,
            email = form.email.data,
            password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        )
        user.save()
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


# TODO: implement
@users.route("/login", methods=["GET", "POST"])
def login():
    loginForm = LoginForm()
    #Check if authenticated
    if current_user.is_authenticated:
        return redirect(url_for('recipes.index'))

    if loginForm.validate_on_submit():
        user = User.objects(username=loginForm.username.data).first()
        
        if user and bcrypt.check_password_hash(user.password, loginForm.password.data):
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            flash("Login failed. Check your username and/or password", "danger")
    
    return render_template('login.html', form=loginForm)


# TODO: implement
@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('recipes.index'))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_username_form = UpdateUsernameForm()
    update_profile_pic_form = UpdateProfilePicForm()
    image = None

    if request.method == "POST":
        # Update username
        if update_username_form.submit_username.data and update_username_form.validate():
            current_user.username = update_username_form.username.data  # Corrected variable name
            current_user.save()
            flash("Username updated successfully.")
            return redirect(url_for('users.account'))

        # Update profile picture
        if update_profile_pic_form.submit_picture.data and update_profile_pic_form.validate():
            pic = update_profile_pic_form.picture.data  # Corrected variable name
            if pic is None:
                current_user.profile_pic = None
                current_user.save()
            else:
                if current_user.profile_pic.get() is None:
                    current_user.profile_pic.put(pic.stream, content_type=pic.content_type)
                else:
                    current_user.profile_pic.replace(pic.stream, content_type=pic.content_type)
                current_user.save()
                return redirect(url_for('users.account'))
    else:
           # Load the current user's profile picture for GET requests
        image = get_b64_img(current_user.username) if current_user.profile_pic else None

    return render_template("account.html",
                           update_username_form=update_username_form, 
                           update_profile_pic_form=update_profile_pic_form, 
                           image=image)

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        {# Profile picture #}
        <img style="border-radius: 1rem; margin-top: 1rem; margin-bottom: 1rem;" src="data:image/png;base64,{{image}}" alt="image">
    {% endif %}

    {# TODO: Greeting (must include the current user's username) #}
    <h2 class="text-2xl" style="font-weight: bolder;">Welcome, {{ current_user.username }}!</h2>

</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl" style="font-weight: bold; margin-top: 0.5rem;">
        Update Username
    </h3>
    <form class="review-form" style="margin-top: 0.5rem;" method="POST" action="">
        {{ update_username_form.csrf_token }}
        <div class="form-group">
            {{ update_username_form.username.label(style="color: white;") }}
            {{ update_username_form.username(class="form-content", style="margin-top: 0.5rem;") }}
            {% if update_username_form.username.errors %}
            <div class="error" role="alert">
                {% for error in update_username_form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_username_form.submit_username(class="review-button") }}
    </form>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h3 class="text-xl" style="font-weight: bold;">
        Update Profile Picture
    </h3>
    <form class="review-form" style="margin-top: 0.5rem;" method="POST" action="" enctype="multipart/form-data">
        {{ update_profile_pic_form.csrf_token }}
        <div class="form-group">
            {{ update_profile_pic_form.picture.label(style="color: white;") }}
            {{ update_profile_pic_form.picture(class="form-content", style="margin-top: 0.5rem;") }}
            {% if update_profile_pic_form.picture.errors %}
            <div class="error" role="alert">
                {% for error in update_profile_pic_form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ update_profile_pic_form.submit_picture(class="review-button") }}
    </form>
</div>

<div class="flex justify-center">
    {# TODO: Link to see all of the current user's reviews. #}
    <a href="{{ url_for('recipes.user_detail', username=current_user.username) }}" class="review-button-link">All Reviews</a>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="{{url_for('static',filename='compiled.css')}}"
    />
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Recipe Hub</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}
</body>
</html>

flask_app/templates/error.html
{% extends "header.html" %}
{% block content %}
<h2 class="text-2xl text-neutral-600 text-center flex items-center justify-center h-[calc(100vh-10rem)]">
    {{ error_msg }}
    <a class="text-blue-400 hover:text-blue-400 duration-150" href="/"> Return</a>
</h2>
{% endblock %}

flask_app/templates/header.html
{% extends "base.html" %} {% block header %}
<nav class="navbar flex w-full justify-between z-40">
    <a class="m-5 navlink" href="{{ url_for('recipes.index') }}">
        <span class="hidden sm:block">Recipe Hub</span>
        <span class="block sm:hidden">Home</span>
    </a>
    {% if current_user.is_authenticated %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.account') }}">Account</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.logout') }}">Logout</a>
    </div>
    {% else %}
    <div class="flex">
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.login') }}">Login</a>
        <a class="my-5 mr-5 ml-0 navlink" href="{{ url_for('users.register') }}">Register</a>
    </div>
    {% endif %}
</nav>
{% block content %}{% endblock %}{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %} {% block content %}
<div class="main-container">
  <h2 class="main-title">Discover Recipes</h2>
  <form class="searchbar" action="/" method="POST">
    {{ form.csrf_token }}
    {{ form.search_query(class="form-control", placeholder="Find a recipe") }}
    {{ form.submit(class="form-button") }}
  </form>
  <h2 class="explore-title">Explore Recipes</h2>
  <div class="results-container">
    {% if form.search_query.errors %}
    <div class="error" role="alert">
      {% for error in form.search_query.errors %}
      <span>{{ error }}</span>
      {% endfor %}
    </div>
    {% endif %}

    {% if error_msg %}
    <div class="error" role="alert">
      {{ error_msg }}
    </div>
    {% endif %}

    {% for random in random_recipes %}
    <a href="{{ url_for('recipes.recipe_detail', recipe_id=random.recipe_id) }}" class="group recipe-card">
      <img src="{{ random.image }}" class="recipe-card-img" alt="missing image" />
      <h5 class="recipe-card-content"> {{ random.title }} </h5>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Log In</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you don't have an account, <a class="text-blue-400 duration-150 hover:text-blue-400 underline" href="{{ url_for('users.register') }}">register here</a>.
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    {# show flashed messages if an authentication error occurs #}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="error" role="alert">
                    <span>{{ message }}</span>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %} 
{% block content %}

<div class="results-container">
  {% if error_msg %}
  <div class="error" role="alert">
    {{ error_msg }}
  </div>
  {% endif %}
  {% for result in results %}
  <a href="{{ url_for('recipes.recipe_detail', recipe_id=result.id) }}" class="group recipe-card">
    <img src="{{ result.image }}" class="recipe-card-img" alt="missing image" />
    <h5 class="recipe-card-content"> {{ result.title }} </h5>
  </a>
  {% endfor %}
</div>

<div class="pagination">
  {% if page > 1 %}
    <a href="{{ url_for('recipes.query_results', query=query, page=page-1) }}">Previous</a>
  {% endif %}
    <span>Page {{ page }} of {{ total_pages }}</span>
  {% if page < total_pages %}
    <a href="{{ url_for('recipes.query_results', query=query, page=page+1) }}">Next</a>
  {% endif %}
</div>

{% endblock %}

flask_app/templates/recipe_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b class="text-red-400">
  {{ error_msg }}
</b>
{% endif %} 



{# Display card for the recipe details #}
<div>
  <div class="recipe">
    <h1>{{ recipe.title }}</h1>
    <img alt="No Image" src="{{ recipe.image }}" />
    <p>Cook: {{ recipe.readyInMinutes }} minutes | Servings: {{ recipe.servings }} | Rating: {{ recipe.score }}/100</p>
  </div>
  <div class="summary">
    <p>{{ recipe.summary | safe }}</p>
  </div>

  <div class="ing">
      <h5>Ingredients:</h5>
      {% for item in recipe.ingredients %}
        <label>
          <input type="checkbox" name="{{ item }}">
          {{ item }}
        </label>
        <br>
      {% endfor %}
  </div>
  
  
  <div class="steps">
    <h5>Instructions: </h5>
    <ol>
      {% if recipe.instructions %}
        {% for number, step in recipe.instructions.items() %}
        <li>{{ number }}. {{ step }}</li>
        {% endfor %}
      {% endif %}
    </ol>
  </div>
  
  {# Reviews #}
  <div class="reviews">
    <h1 class="reviews-title"> Reviews
      <small class="reviews-count"> {{ reviews | length }} reviews </small>
      {# Calculate and display the average rating as stars next to the review count #}
      <small class="average-rating">
        {% if reviews | length > 0 %}
          {% set total_rating = reviews | map(attribute='rating') | sum %}
          {% set average_rating = total_rating / (reviews | length) %}
          {% set rounded_rating = average_rating | round %}
          {% for i in range(6, 1, -1) %}
            {% if i <= (rounded_rating or 0) %}
              <span class="star-empty">&#9734;</span>
            {% else %}
              <span class="star-filled">&#9733;</span>
            {% endif %}
          {% endfor %}
        {% endif %}
      </small>
    </h1>
    <ul class="review-container">
      {% for review in reviews %}
        <li class="review flex gap-2">
          <img class="h-20 w-20 rounded-lg" src="data:image/png;base64,{{ review.image }}" alt="No Image" />
          <div class="w-full">
            <span class="review-date">{{ review.date }}</span>
            <a class="review-commenter" href="{{ url_for('recipes.user_detail', username=review.commenter.username) }}">
              {{ review.commenter.username }}
            </a>
            <div class="review-rating">
              {% for i in range(6, 1, -1) %}
                {% if i <= (review.rating or 0) %}
                  <span>&#9734;</span>
                {% else %}
                  <span class="star-filled">&#9733;</span>  
                {% endif %}
              {% endfor %}
            </div>
            <p class="review-content">{{ review.content }}</p>
          </div>
        </li>
      {% endfor %}
    </ul>

    {% if current_user.is_authenticated %}
      {# Recipe review submission form #}
      <div class="container mx-auto">
        <form method="POST" action="" class="review-form">
          {{ form.csrf_token }}
          
          <div class="form-group review-input">
            {{ form.text.label }} 
            {{ form.text(class="form-content") }}
            {% if form.text.errors %}
              <div class="error" role="alert">
                {% for error in form.text.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>
          
          <div class="form-group review-rating">
            <label for="rating">Rating: </label>
            <div class="star-rating" id="star-rating">
              {% for i in range(1, 6) %}
                <input type="radio" id="star{{ i }}" name="rating" value="{{ i }}" {% if form.rating.data == i %} checked {% endif %} />
                <label for="star{{ i }}" class="star">&#9733;</label>
              {% endfor %}
            </div>
            {% if form.rating.errors %}
              <div class="error" role="alert">
                {% for error in form.rating.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% endif %}
          </div>

          {{ form.submit(class="review-button") }}
        </form>
      </div>
    {% endif %}
  </div>
  <div class="w-0 lg:w-96"></div>
</div>

{% endblock content %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h2 class="text-2xl font-bold text-center">Registration</h2>
</div>
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3 text-center my-2">
    If you already have an account, <a class="text-blue-400 duration-150 hover:text-blue-400 underline" href="{{ url_for('users.login') }}">login here</a>.
</div>
<!-- Registration Form: -->
<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">

    <form class="review-form" method="POST" action="">
        {{ form.csrf_token }}
        <div class="form-group review-input">
            {{ form.username.label }}
            {{ form.username(class="form-content") }}
            {% if form.username.errors %}
            <div class="error" role="alert">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.email.label }}
            {{ form.email(class="form-content") }}
            {% if form.email.errors %}
            <div class="error" role="alert">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.password.label }}
            {{ form.password(class="form-content") }}
            {% if form.password.errors %}
            <div class="error" role="alert">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div class="form-group review-input">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-content") }}
            {% if form.confirm_password.errors %}
            <div class="error" role="alert">
                {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        {{ form.submit(class="review-button") }}
    </form>

</div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}

{% block content %}
{% if error %}
    <b class="text-red-400" role="alert">
        {{ error }}
    </b>
{% endif %}

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    {% if image %}
        {# User's Profile Picture #}
        <img class="rounded-2xl w-full" src="data:image/png;base64,{{ image }}" alt="image">
    {% endif %}
    <h2 class="text-4xl font-bold my-4">{{ user.username }}'s Reviews</h2>
</div>

<div class="container mx-auto w-full md:w-2/3 lg:w-1/3">
    <h4 class="text-2xl text-neutral-500 font-bold">Number of Reviews: <b style="font-weight: bold;">{{ reviews|length }}</b></h4>
    <table style="margin-top: 0.5rem;">
        <thead>
            <tr>
                <th class="account-border">Date</th>
                <th class="account-border">Recipe</th>
                <th class="account-border">Comment</th>
                <th class="account-border">Rating</th>
            </tr>
        </thead>
        <tbody>
            {% for review in reviews %}
                <tr>
                    <td class="account-border">{{ review.date }}</td>
                    <td class="account-border">{{ review.recipe_title }}</td>
                    <td class="account-border">{{ review.content }}</td>
                    <td class="account-border">
                        <div class="stars-container">
                            {% for i in range(1, 6) %}
                                {% if i <= review.rating %}
                                    <span class="star-filled">&#9733;</span>       
                                {% else %}
                                    <span class="star-empty">&#9734;</span>   
                                {% endif %}
                            {% endfor %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}